Add CMake support
ARMmbed/mbed-os-atecc608a pull request #16
Opened 2020-11-17 16:01 UTC by rajkan01

- Added CMakeLists.txt to build this lib with CMake

@Patater @0xc0170 @hugueskamba

2020-11-18 10:51 UTC, hugueskamba submitted a review, later dismissed

2020-11-20 10:19 UTC, Patater approved these changes

2020-11-20 10:22 UTC, Patater requested changes
Actually, could you please update the mbed-cryptoauthlib.lib file to latest? Thanks

2020-11-24 09:41 UTC, Patater approved these changes

2020-11-24 09:41 UTC, merged